name: MacOS(Unix ARM)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Pyinstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build
      run: |
        pyinstaller C++Tester.py
    - name: Copy License
      run: |
        cp LICENSE dist/C++Tester/LICENSE
        cp README.md dist/C++Tester/README.md
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: C++Tester
        path: dist/*
